export type Money = string; // Integer poisha (1/100 BDT), never floating-point JSON money.
export type Unit = 'piece' | 'bottle' | 'pack' | 'carton' | 'bag';
export type StockStatus = 'in_stock' | 'low_stock' | 'out_of_stock';
export type IconKey = 'package' | 'bottle' | 'bag' | 'bread' | 'milk' | 'store';
export type ColorKey = 'emerald' | 'amber' | 'blue' | 'rose' | 'violet' | 'sand';
export type CatalogKind = 'products' | 'categories' | 'suppliers';
export type DocumentKind = 'purchases' | 'sales' | 'movements';
export type ReportKind = 'sales' | 'purchases' | 'inventory';
export interface Store { id: string; owner_user_id: string; name: string; phone: string | null; address: string | null; currency: 'BDT'; timezone: 'Asia/Dhaka'; is_demo: boolean; data_revision: string; }
export interface Profile { id: string; display_name: string; }
export interface CatalogBase { id: string; name: string; version: number; store_id: string; created_at: string; updated_at: string; }
export interface Category extends CatalogBase { description: string | null; icon_key: IconKey; color_key: ColorKey; product_count: number; }
export interface Supplier extends CatalogBase { phone: string | null; address: string | null; archived_at: string | null; received_count: number; received_total_paisa: Money; }
export interface Product extends CatalogBase { sku: string; category_id: string; category_name: string; unit: Unit; reference_cost_paisa: Money; selling_price_paisa: Money; minimum_stock: number; quantity: number; stock_status: StockStatus; stock_value_paisa: Money; description: string | null; icon_key: IconKey; color_key: ColorKey; archived_at: string | null; referenced: boolean; }
export interface AttentionProduct { id: string; name: string; sku: string; unit: Unit; quantity: number; minimum_stock: number; shortage: number; stock_status: StockStatus; icon_key: IconKey; color_key: ColorKey; }
export interface InventorySummary { active_count: number; category_count: number; in_stock: number; low_stock: number; out_of_stock: number; attention_count: number; units: number; value_paisa: Money; }
export interface ActivitySummary { count: number; total_paisa: Money; units: number; discount_paisa?: Money; subtotal_paisa?: Money; average_paisa?: Money; cogs_paisa?: Money; net_profit_paisa?: Money; }
export interface ValueCategory { id: string; name: string; value_paisa: Money; product_count: number; }
export interface RecentActivity { id: string; number: string; kind: 'sale' | 'purchase'; total_paisa: Money; activity_at: string; detail: string; }
export interface Workspace { store: Store; profile: Profile; snapshot_at: string; business_date: string; data_revision: string; inventory: InventorySummary; sales: ActivitySummary; purchases: ActivitySummary; attention: AttentionProduct[]; attention_truncated: boolean; categories: ValueCategory[]; highest_category: ValueCategory | null; recent: RecentActivity[]; }
export interface PageResult<T> { rows: T[]; total: number; page: number; size: number; total_paisa?: Money; discount_paisa?: Money; received_total_paisa?: Money; filtered_value_paisa?: Money; units?: number; all_count?: number; received_count?: number; draft_count?: number; }
export interface PurchaseItem { id: string; product_id: string; line_position: number; quantity: number; unit_cost_paisa: Money; line_total_paisa: Money; product_name_snapshot: string; sku_snapshot: string; unit_snapshot: Unit; name: string; sku: string; unit: Unit; quantity_available: number; icon_key: IconKey; color_key: ColorKey; }
export interface Purchase { id: string; number: string; supplier_id: string; supplier_name: string; status: 'draft' | 'received'; purchase_date: string; received_at: string | null; updated_at: string; activity_at: string; supplier_reference: string | null; note: string | null; total_paisa: Money; version: number; product_count: number; units: number; supplier_name_snapshot: string | null; supplier_phone_snapshot: string | null; supplier_address_snapshot: string | null; store_name_snapshot: string | null; store_phone_snapshot: string | null; store_address_snapshot: string | null; items: PurchaseItem[]; movements: Movement[]; }
export interface SaleItem { id: string; product_id: string; line_position: number; product_name_snapshot: string; sku_snapshot: string; unit_snapshot: Unit; quantity: number; unit_price_paisa: Money; line_gross_paisa: Money; unit_cost_paisa: Money; line_cost_paisa: Money; }
export interface Sale { id: string; number: string; completed_at: string; status: 'completed'; customer_name: string | null; customer_phone: string | null; subtotal_paisa: Money; discount_paisa: Money; total_paisa: Money; cash_received_paisa: Money; change_paisa: Money; cashier_name_snapshot: string; store_name_snapshot: string; store_phone_snapshot: string | null; store_address_snapshot: string | null; units: number; product_count: number; items: SaleItem[]; }
export interface Movement { id: string; sequence: string; product_id: string; product_name: string; sku: string; unit: Unit; icon_key: IconKey; color_key: ColorKey; source_type: 'purchase' | 'sale'; source_id: string; number: string; quantity_delta: number; quantity_before: number; quantity_after: number; created_at: string; }
export interface ReportRow { id: string; name: string; sku: string; quantity: number; gross_paisa?: Money; cost_paisa?: Money; gross_profit_paisa?: Money; total_paisa?: Money; min_cost_paisa?: Money; max_cost_paisa?: Money; value_paisa?: Money; }
export interface Report { kind: ReportKind; snapshot_at: string; business_date: string; from?: string; to?: string; summary: ActivitySummary & InventorySummary; rows: (ReportRow & Product)[]; chart: (ReportRow & ValueCategory)[]; suppliers?: { id: string; name: string; count: number; total_paisa: Money }[]; total: number; page: number; size: number; source_count: number; source_rows: Record<string, string | number | null>[]; filtered_value_paisa?: Money; }
export interface OperationResult { id: string; number?: string; version?: number; status?: string; already_received?: boolean; total_paisa?: Money; change_paisa?: Money; }
export type Filters = { q?: string; page?: number; size?: number; sort?: string; category?: string; stock?: string; archived?: boolean; status?: string; from?: string; to?: string; supplier?: string; product?: string; document?: string };
