'use client';
import Link from 'next/link';
import { useActionState, useState } from 'react';
import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, Mail, Store } from 'lucide-react';
import { Logo, PackageArt } from '@/components/brand';
import { Field, Notice } from '@/components/ui';
import { authenticate } from '@/app/auth/actions';
export type AuthMode='register'|'login'|'forgot-password'|'reset-password';
export function AuthScreen({mode,next='',configured=true}:{mode:AuthMode;next?:string;configured?:boolean}){
 const [state,action,pending]=useActionState(authenticate.bind(null,mode),{message:''});const [values,setValues]=useState<Record<string,string>>({});const [visible,setVisible]=useState(false);
 const registration=mode==='register',recovery=mode==='forgot-password',reset=mode==='reset-password';
 const title=registration?'Create your account':recovery?'Reset your password':reset?'Choose a new password':'Welcome back';
 const pitch=registration?'A clearer store.\nA fresh start.':recovery||reset?'Let’s get you\nback to work.':'Everything\nin its place.';
 function input(name:string,label:string,type='text',placeholder='',hint?:string){const error=state.fields?.[name]?.[0];return <Field key={name} id={name} label={label} hint={hint} error={error}><div className={type==='password'?'input-with-button':undefined}><input id={name} name={name} type={type==='password'&&visible?'text':type} placeholder={placeholder} required value={values[name]??''} onChange={e=>setValues(v=>({...v,[name]:e.target.value}))} autoComplete={name==='full_name'?'name':name==='email'?'email':name==='password'?(registration||reset?'new-password':'current-password'):name==='confirm_password'?'new-password':'organization'} minLength={type==='password'&&(registration||reset)?8:undefined} maxLength={type==='password'?128:100} aria-invalid={!!error} aria-describedby={error?`${name}-error`:hint?`${name}-hint`:undefined} style={{width:'100%'}}/>{type==='password'&&<button type="button" className="icon-button" aria-label={visible?'Hide passwords':'Show passwords'} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button>}</div></Field>}
 return <div className={`auth-layout ${registration?'register':''}`}><aside className="auth-aside"><Logo/><div className="auth-pitch"><h2>{pitch}</h2><p>{registration?'Keep your products, purchases and sales together, from day one.':recovery||reset?'Recover access to your account and return to your inventory.':'Your next purchase, your next sale, and a clear view of the stock in between.'}</p></div><PackageArt/><small>A single workspace for your store.</small></aside><main className="auth-main"><Link href="/" className="back-home"><ArrowLeft size={12}/>Back to home</Link><div className="auth-form-area">{!registration&&<span className="swatch">{recovery||reset?<LockKeyhole size={21}/>:<Store size={21}/>}</span>}<h1>{title}</h1><p>{registration?'Set up your own store workspace in a few steps.':recovery?'Enter the email address used for your account.':reset?'Use a password with at least eight characters.':'Log in to continue to your store.'}</p>{!configured&&<div className="form-message"><Notice tone="warning">This deployment still needs its dedicated Supabase connection. Authentication is not yet enabled.</Notice></div>}{state.message&&<div className="form-message"><Notice tone={state.success?'success':'error'}>{state.message}</Notice></div>}<form action={action}><input type="hidden" name="next" value={next}/><fieldset disabled={pending||!configured}>{registration&&input('full_name','Full name','text','Your full name')}{registration&&input('store_name','Store name','text','Your store name')}{!reset&&input('email','Email address','email','you@example.com')}{!recovery&&input('password',reset?'New password':'Password','password',registration?'Create a password':'Enter your password',registration?'Use at least 8 characters.':undefined)}{(registration||reset)&&input('confirm_password','Confirm password','password','Re-enter your password')}{mode==='login'&&<div className="auth-links"><label><input type="checkbox" name="remember"/>Remember me</label><Link href="/forgot-password">Forgot password?</Link></div>}<button className="button primary full" type="submit">{pending?'Please wait…':<>{recovery?<Mail size={15}/>:<ArrowRight size={15}/>} {registration?'Create account':recovery?'Send reset link':reset?'Update password':'Log in'}</>}</button></fieldset></form><p className="switch-auth">{registration?'Already have an account?':mode==='login'?'New to Smart Inventory?':'Remember your password?'}<Link href={mode==='login'?'/register':'/login'}>{mode==='login'?'Create an account':registration?'Log in':'Back to log in'}</Link></p>{recovery&&<div style={{marginTop:22}}><Notice>We will send password-reset instructions if an account exists for this email.</Notice></div>}{reset&&<p className="switch-auth"><Link href="/forgot-password">Request a new reset link</Link></p>}</div><footer className="auth-footer"><span>Smart Inventory · Inventory &amp; POS</span><span>{new Date().getFullYear()}</span></footer></main></div>;
}
