import Link from 'next/link';
import {Plus} from 'lucide-react';
import {Heading,Stat,Card,Table,ProductLabel,Status,Pagination,Empty,queryLink} from '@/components/ui';
import {FiltersBar} from '@/components/filters';
import {CatalogFilter} from './catalog-filter';
import {CatalogActions} from './catalog-actions';
import {CatalogEditor} from './catalog-editor';
import {catalog,entity,pageWorkspace} from '@/lib/server/data';
import {parseFilters} from '@/lib/schemas';
import {money} from '@/lib/money';
import type {Product,Category,Supplier} from '@/lib/domain';
export type SearchParams=Record<string,string|string[]|undefined>;
export async function ProductsPage({params}:{params:SearchParams}){
 const filters=parseFilters(params);const [data,w,category]=await Promise.all([catalog<Product>('products',filters),pageWorkspace(),filters.category?entity<Category>('categories',filters.category):Promise.resolve(null)]);
 return <><Heading eyebrow="Workspace / Catalog" title="Products" description="Keep your product details organized. Stock updates through purchases and sales." actions={<Link href="/products/new" className="button primary"><Plus size={15}/>Add product</Link>}/><div className="stats three"><Stat label="Active products" value={w.inventory.active_count} note="Across your whole active catalog"/><Stat label="Categories in use" value={w.inventory.category_count} note="Organized product groups" color="blue"/><Stat label="Products to review" value={w.inventory.attention_count} note={`${w.inventory.low_stock} low · ${w.inventory.out_of_stock} out of stock`} color="amber"/></div><nav className="tabs" aria-label="Catalog lifecycle"><Link className={!filters.archived?'active':''} href={queryLink('/products',params,{archived:undefined,page:undefined})}>Active catalog</Link><Link className={filters.archived?'active':''} href={queryLink('/products',params,{archived:'true',page:undefined})}>Archived products</Link></nav><FiltersBar stock sort><CatalogFilter initial={category}/></FiltersBar><Card><Table headers={['Product','Category','Selling price','Stock','Status','Actions']} empty={!data.rows.length?<Empty title="No products found" description={filters.q||filters.category||filters.stock?'Try another search or clear the filters.':'Add products, then receive a purchase to put them in stock.'} href="/products/new" action="Add product"/>:undefined}>{data.rows.map(p=><tr key={p.id}><td><ProductLabel name={p.name} sku={p.sku} icon_key={p.icon_key} color_key={p.color_key}/></td><td>{p.category_name}</td><td><strong>{money(p.selling_price_paisa)}</strong></td><td><strong>{p.quantity}</strong> {p.unit}</td><td>{p.archived_at?<span className="badge">Archived</span>:<Status status={p.stock_status}/>}</td><td className="actions"><CatalogActions kind="product" record={p}/></td></tr>)}</Table><Pagination data={data} path="/products" params={params}/></Card></>;
}
export async function CategoriesPage({params}:{params:SearchParams}){
 const filters=parseFilters(params);const data=await catalog<Category>('categories',filters);
 return <><Heading eyebrow="Workspace / Catalog" title="Categories" description="Group related products for a clearer catalog and reports." actions={<CatalogEditor kind="category"/>}/><div className="stats three"><Stat label="Matching categories" value={data.total} note="Search applies to this count"/><Stat label="Category status" value="Active" note="Reassign products before deleting a category" color="blue"/><Stat label="Organization" value="One store" note="Categories belong only to your store" color="amber"/></div><FiltersBar/><Card><Table headers={['Category','Description','Products','Status','Actions']} empty={!data.rows.length?<Empty title="No categories found" description="Create your first category or try a different search."/>:undefined}>{data.rows.map(c=><tr key={c.id}><td><ProductLabel name={c.name} icon_key={c.icon_key} color_key={c.color_key}/></td><td style={{maxWidth:320,whiteSpace:'normal'}}>{c.description||'Not provided'}</td><td>{c.product_count} products</td><td><span className="badge in_stock">Active</span></td><td className="actions"><CatalogActions kind="category" record={c}/></td></tr>)}</Table><Pagination data={data} path="/categories" params={params}/></Card></>;
}
export async function SuppliersPage({params}:{params:SearchParams}){
 const filters=parseFilters(params),data=await catalog<Supplier>('suppliers',filters);
 return <><Heading eyebrow="Workspace / Suppliers" title="Suppliers" description="Manage the people and businesses you purchase stock from." actions={<CatalogEditor kind="supplier"/>}/><div className="stats three"><Stat label="Matching suppliers" value={data.total} note="Current search and archive filter" icon="store"/><Stat label="Received purchases" value={data.received_count??0} note="Lifetime · drafts excluded" color="blue" icon="bag"/><Stat label="Received purchase value" value={money(data.received_total_paisa??'0')} note="Goods received, not a supplier balance" color="amber"/></div><nav className="tabs" aria-label="Supplier lifecycle"><Link className={!filters.archived?'active':''} href={queryLink('/suppliers',params,{archived:undefined,page:undefined})}>Active suppliers</Link><Link className={filters.archived?'active':''} href={queryLink('/suppliers',params,{archived:'true',page:undefined})}>Archived suppliers</Link></nav><FiltersBar/><Card><Table headers={['Supplier','Phone','Address','Received purchases','Received value','Actions']} empty={!data.rows.length?<Empty title="No suppliers found" description="Add a supplier before recording your first purchase."/>:undefined}>{data.rows.map(s=><tr key={s.id}><td><ProductLabel name={s.name} icon_key="store" color_key="blue"/></td><td>{s.phone||'Not provided'}</td><td style={{maxWidth:220,whiteSpace:'normal'}}>{s.address||'Not provided'}</td><td>{s.received_count}</td><td><strong>{money(s.received_total_paisa)}</strong></td><td className="actions"><CatalogActions kind="supplier" record={s}/></td></tr>)}</Table><Pagination data={data} path="/suppliers" params={params}/></Card></>;
}
