'use client';
import {useId,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {Plus,Pencil} from 'lucide-react';
import {Dialog} from '@/components/dialog';
import {Field,Notice} from '@/components/ui';
import {ProductIcon} from '@/components/brand';
import {OperationFeedback} from '@/components/operation-feedback';
import {useOperation} from '@/lib/client/use-operation';
import {useWorkspace} from '@/components/workspace-context';
import type {Category,Supplier,OperationResult} from '@/lib/domain';
export function AppearanceFields({icon,color,onIcon,onColor}:{icon:string;color:string;onIcon:(value:string)=>void;onColor:(value:string)=>void}){
 return <><div className="field"><label>Product icon</label><div className="segmented">{['package','bottle','bag','bread','milk','store'].map(value=><button key={value} type="button" aria-label={`${value} icon`} aria-pressed={icon===value} className={icon===value?'active':''} onClick={()=>onIcon(value)}><ProductIcon icon={value} color={color} size={18}/></button>)}</div></div><div className="field"><label>Color preset</label><div className="segmented">{['emerald','amber','blue','rose','violet','sand'].map(value=><button type="button" key={value} aria-label={`${value} color`} aria-pressed={color===value} className={color===value?'active':''} onClick={()=>onColor(value)}><span className={`swatch ${value}`} style={{width:20,height:20}}><span aria-hidden="true">●</span></span></button>)}</div></div></>;
}
export function CatalogEditor({kind,record,onSaved,compact=false}:{kind:'category'|'supplier';record?:Category|Supplier;onSaved?:(value:{id:string;name:string})=>void;compact?:boolean}){
 const [open,setOpen]=useState(false);const workspace=useWorkspace();const router=useRouter();const prefix=useId();
 const [name,setName]=useState(record?.name??'');const [description,setDescription]=useState(record&&'description'in record?record.description??'':'');const [phone,setPhone]=useState(record&&'phone'in record?record.phone??'':'');const [address,setAddress]=useState(record&&'address'in record?record.address??'':'');const [icon,setIcon]=useState(record&&'icon_key'in record?record.icon_key:'package');const [color,setColor]=useState(record&&'color_key'in record?record.color_key:'emerald');
 const operation=useOperation(`${workspace.store.id}:${kind}:${record?.id??'new'}`);
 function success(result:OperationResult){setOpen(false);onSaved?.({id:result.id,name});router.refresh();if(!record){setName('');setDescription('');setPhone('');setAddress('');}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const payload={...(record?{id:record.id,expected_version:record.version}:{}),name,...(kind==='category'?{description,icon_key:icon,color_key:color}:{phone,address})};const result=await operation.submit({operation:'catalog',kind,action:'save',payload});if(result)success(result);}
 const label=`${record?'Edit':'Add'} ${kind}`;
 return <><button type="button" className={record?'icon-button':compact?'text-link':'button primary'} aria-label={label+(record?` ${record.name}`:'')} onClick={()=>setOpen(true)}>{record?<Pencil size={16}/>:<><Plus size={15}/>{label}</>}</button><Dialog open={open} title={label} onClose={()=>{if(!operation.locked)setOpen(false);}}><OperationFeedback operation={operation} onSuccess={success}/><form onSubmit={submit}><fieldset disabled={operation.locked}><Field id={`${prefix}-name`} label={`${kind==='category'?'Category':'Supplier'} name`}><input id={`${prefix}-name`} value={name} onChange={e=>setName(e.target.value)} maxLength={kind==='category'?80:150} required autoFocus/></Field>{kind==='category'?<><Field id={`${prefix}-description`} label="Description (optional)"><textarea id={`${prefix}-description`} value={description} maxLength={1000} onChange={e=>setDescription(e.target.value)}/></Field><AppearanceFields icon={icon} color={color} onIcon={setIcon} onColor={setColor}/></>:<><Field id={`${prefix}-phone`} label="Phone (optional)"><input id={`${prefix}-phone`} type="tel" value={phone} maxLength={32} onChange={e=>setPhone(e.target.value)}/></Field><Field id={`${prefix}-address`} label="Address (optional)"><textarea id={`${prefix}-address`} value={address} maxLength={500} onChange={e=>setAddress(e.target.value)}/></Field></>}<div className="form-actions"><button type="button" className="button" onClick={()=>setOpen(false)}>Cancel</button><button type="submit" className="button primary">{operation.busy?'Saving…':`Save ${kind}`}</button></div></fieldset></form></Dialog></>;
}
export function StoreEditor({open,onClose}:{open:boolean;onClose:()=>void}){
 const {store,profile}=useWorkspace();const router=useRouter();const [name,setName]=useState(store.name),[display,setDisplay]=useState(profile.display_name),[phone,setPhone]=useState(store.phone??''),[address,setAddress]=useState(store.address??'');const operation=useOperation(`${store.id}:store`);
 function success(){onClose();router.refresh();}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const result=await operation.submit({operation:'catalog',kind:'store',action:'save',payload:{name,display_name:display,phone,address}});if(result)success();}
 return <Dialog open={open} onClose={()=>{if(!operation.locked)onClose();}} title="Store information"><OperationFeedback operation={operation} onSuccess={success}/><form onSubmit={submit}><fieldset disabled={operation.locked}><Field id="store-name" label="Store name"><input id="store-name" required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></Field><Field id="owner-name" label="Owner name"><input id="owner-name" required minLength={2} maxLength={100} value={display} onChange={e=>setDisplay(e.target.value)}/></Field><Field id="store-phone" label="Store phone (optional)"><input id="store-phone" type="tel" maxLength={32} value={phone} onChange={e=>setPhone(e.target.value)}/></Field><Field id="store-address" label="Store address (optional)"><textarea id="store-address" maxLength={500} value={address} onChange={e=>setAddress(e.target.value)}/></Field><Notice>One store · BDT · Asia/Dhaka. Changes apply to future documents; existing receipt snapshots stay unchanged.</Notice><div className="form-actions" style={{marginTop:20}}><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" type="submit">{operation.busy?'Saving…':'Save changes'}</button></div></fieldset></form></Dialog>;
}
