'use client';
import {useState} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import {Download} from 'lucide-react';
import {Notice} from '@/components/ui';
import {dateSpan,validCalendarDate} from '@/lib/dates';
import type {ReportKind} from '@/lib/domain';
export function ReportPeriod({from,to}:{from:string;to:string}){const path=usePathname(),router=useRouter(),params=useSearchParams();const [first,setFirst]=useState(from),[last,setLast]=useState(to),[error,setError]=useState('');function apply(){if(!validCalendarDate(first)||!validCalendarDate(last)||dateSpan(first,last)<1||dateSpan(first,last)>366){setError('Choose a valid date range of at most 366 days.');return;}setError('');const next=new URLSearchParams(params);next.set('from',first);next.set('to',last);next.delete('page');router.replace(path+'?'+next,{scroll:false});}return <div className="no-print" style={{marginBottom:22}}><div className="date-filters"><label>From<input type="date" value={first} onChange={e=>setFirst(e.target.value)}/></label><label>To<input type="date" value={last} onChange={e=>setLast(e.target.value)}/></label><button type="button" className="button" onClick={apply}>Apply period</button><span className="muted small">Posting dates · Asia/Dhaka</span></div>{error&&<p className="field-error">{error}</p>}</div>}
export function ExportButton({kind}:{kind:ReportKind}){const params=useSearchParams();const [busy,setBusy]=useState(false),[error,setError]=useState('');async function download(){setBusy(true);setError('');try{const response=await fetch(`/api/reports/${kind}/export?${params}`,{cache:'no-store'});if(!response.ok){const data=await response.json();throw new Error(data.error?.message??'Export could not be completed.');}const blob=await response.blob(),url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1]??`${kind}-report.csv`;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}catch(e){setError(e instanceof Error?e.message:'Export could not be completed.');}finally{setBusy(false);}}return <div><button type="button" className="button" disabled={busy} onClick={()=>void download()}><Download size={15}/>{busy?'Preparing export…':'Export CSV'}</button>{error&&<Notice tone="error">{error}</Notice>}</div>}
