import test from 'node:test';
import assert from 'node:assert/strict';
import {provider,validateOutput,readJson} from '../api/_lib/ai.js';
import {createHandler} from '../api/assistant.js';
const line={sku:'RICE-1',name:'Rice',quantity:2,unit_cost_minor:123,confidence:.8,warning:''};
const draft={kind:'purchase_draft',lines:[line],warnings:[]};
const config={SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fixture_not_real_1234567890'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
function req(body={task:'purchase',org_id:'11111111-1111-4111-8111-111111111111',text:'RICE-1, 2, 1.23'}){return {method:'POST',headers:{host:'inventory.example','content-type':'application/json',origin:'https://inventory.example',authorization:'Bearer user-token'},body};}
async function invoke(request,fetcher,env=config){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.code=v;return this;},json(v){this.body=v;}};await createHandler(env,fetcher)(request,res);return res;}
test('default provider is honest deterministic rules',async()=>{const p=provider({});assert.equal(p.name,'rules');const r=await p.generate('purchase',{text:'RICE-1, 2, 1.23'},{});assert.equal(r.lines[0].unit_cost_minor,123);assert.ok(r.warnings[0].includes('No AI'));});
test('provider contract rejects negative/fractional quantities and unknown modes',()=>{for(const q of [-1,0,1.5,1000001])assert.throws(()=>validateOutput('purchase',{...draft,lines:[{...line,quantity:q}]}));assert.throws(()=>provider({AI_PROVIDER:'unknown'}));});
test('provider output is whitelisted and mutation fields never escape',()=>{const r=validateOutput('purchase',{...draft,execute_sql:'DROP TABLE products',lines:[{...line,action:'sale_checkout'}]});assert.equal(r.execute_sql,undefined);assert.equal(r.lines[0].action,undefined);});
test('oversized, malformed and refused provider output fails closed',async()=>{await assert.rejects(readJson(new Response('x'.repeat(50)),10));await assert.rejects(readJson(new Response('not-json')));const p=provider({AI_PROVIDER:'openai-compatible',AI_API_KEY:'private',AI_MODEL:'configured'},async()=>json({choices:[{message:{content:null}}]}));await assert.rejects(p.generate('purchase',{text:'x'},{}));});
test('OpenAI-compatible adapter uses server credentials, structured JSON and no tools',async()=>{let call;const p=provider({AI_PROVIDER:'openai-compatible',AI_API_KEY:'private-provider-key',AI_MODEL:'chosen-model'},async(url,options)=>{call={url,options};return json({choices:[{message:{content:JSON.stringify(draft)}}]});});assert.deepEqual(await p.generate('purchase',{text:'untrusted source'},{}),draft);const body=JSON.parse(call.options.body);assert.equal(body.store,false);assert.equal(body.model,'chosen-model');assert.equal(body.tools,undefined);assert.equal(call.options.headers.Authorization,'Bearer private-provider-key');assert.equal(call.options.redirect,'error');});
test('webhook uses same contract and rejects local configured endpoints',async()=>{const env={AI_PROVIDER:'webhook',AI_WEBHOOK_URL:'https://workflow.example/inventory',AI_WEBHOOK_SECRET:'server-secret'};const p=provider(env,async()=>json(draft));assert.deepEqual(await p.generate('purchase',{text:'x'},{}),draft);await assert.rejects(provider({...env,AI_WEBHOOK_URL:'http://127.0.0.1/private'},()=>{}).generate('purchase',{},{}));});
test('assistant rejects method, missing auth and cross-origin requests before HTTP',async()=>{const noFetch=()=>{throw new Error('Unexpected fetch');};let r=req();r.method='GET';assert.equal((await invoke(r,noFetch)).code,405);r=req();delete r.headers.authorization;assert.equal((await invoke(r,noFetch)).code,401);r=req();r.headers.origin='https://other.example';assert.equal((await invoke(r,noFetch)).code,403);});
test('assistant rejects oversized, invalid task and missing server config',async()=>{const noFetch=()=>{throw new Error('Unexpected fetch');};let r=req();r.headers['content-length']='40000';assert.equal((await invoke(r,noFetch)).code,413);r=req();r.body.task='execute-sql';assert.equal((await invoke(r,noFetch)).code,400);assert.equal((await invoke(req(),noFetch,{})).code,503);});
test('assistant requires real auth validation and quota RPC; never mutates stock',async()=>{const calls=[];const r=await invoke(req(),async(url,options)=>{calls.push({url,options});return url.includes('/auth/')?json({id:'user'}):json({dashboard:{},low_stock:[]});});assert.equal(r.code,200);assert.equal(r.body.review_required,true);assert.equal(r.body.provider,'rules');assert.equal(calls.length,2);assert.ok(calls.every(c=>!c.url.includes('si_mutate')));assert.equal(r.headers['Cache-Control'],'no-store');});
test('assistant distinguishes forbidden membership from exhausted quota',async()=>{for(const [message,code] of [['Manager access required',403],['AI hourly limit reached',429]]){const r=await invoke(req(),async url=>url.includes('/auth/')?json({id:'user'}):json({message},400));assert.equal(r.code,code);}});
test('provider network errors never disclose secrets',async()=>{let calls=0;const r=await invoke(req(),async()=>{calls++;if(calls===1)return json({id:'user'});if(calls===2)return json({dashboard:{},low_stock:[]});throw new Error('private-provider-key');},{...config,AI_PROVIDER:'openai-compatible',AI_API_KEY:'private-provider-key',AI_MODEL:'test'});assert.equal(r.code,502);assert.ok(!JSON.stringify(r.body).includes('private-provider-key'));});
