import test from 'node:test';
import assert from 'node:assert/strict';
import {SupabaseClient} from '../src/supabase.js';
const config={supabaseUrl:'https://fixture.supabase.co',supabaseKey:'sb_publishable_fixture_not_real_1234567890'};
const response=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers});
function make(fetcher){const map=new Map();return new SupabaseClient(config,{fetcher,storage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},lock:null});}
const session={access_token:'test-access',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:'test-user'}};
test('requests reject unauthenticated reads before HTTP',async()=>{let calls=0;const c=make(async()=>{calls++;});await assert.rejects(c.select('si_products'),{status:401});assert.equal(calls,0);});
test('PostgREST requests include public key, bearer and exact count',async()=>{let seen;const c=make(async(url,options)=>{seen={url,options};return response([{id:1}],200,{'content-range':'0-0/27'});});c.saveSession(session);const r=await c.select('si_products',{org_id:'eq.workspace',limit:20});assert.equal(r.count,27);assert.equal(seen.options.headers.Authorization,'Bearer test-access');assert.equal(seen.options.headers.apikey,config.supabaseKey);assert.equal(new URL(seen.url).searchParams.get('org_id'),'eq.workspace');});
test('RPC preserves explicit request key and payload',async()=>{let seen;const c=make(async(_,o)=>{seen=JSON.parse(o.body);return response({id:'sale'});});c.saveSession(session);assert.deepEqual(await c.mutate('org','sale_checkout',{lines:[]},'same-key'),{id:'sale'});assert.equal(seen.p_key,'same-key');assert.equal(seen.p_action,'sale_checkout');});
test('concurrent expiration refreshes once',async()=>{let calls=0;const c=make(async(url)=>{calls++;assert.ok(url.includes('refresh_token'));await new Promise(r=>setTimeout(r,5));return response({...session,access_token:'renewed'});});c.saveSession({...session,expires_at:1});assert.deepEqual(await Promise.all([c.token(),c.token(),c.token()]),['renewed','renewed','renewed']);assert.equal(calls,1);});
test('invalid refresh clears session; transport failure retains it',async()=>{const bad=make(async()=>response({message:'invalid refresh'},400));bad.saveSession({...session,expires_at:1});await assert.rejects(bad.token());assert.equal(bad.session,null);const offline=make(async()=>{throw new Error('offline');});offline.saveSession({...session,expires_at:1});await assert.rejects(offline.token(),{code:'NETWORK'});assert.ok(offline.session);});
test('malformed success and interrupted bodies are ambiguous failures',async()=>{const c=make(async()=>new Response('not-json'));await assert.rejects(c.raw('/rest/v1/rpc/si_mutate'),{code:'NETWORK',status:502});});
test('auth callback verifies supplied tokens and removes rejected session',async()=>{const c=make(async()=>response({message:'expired'},401));await assert.rejects(c.callback('#access_token=bad&refresh_token=bad'));assert.equal(c.session,null);});
test('logout clears local credentials even during a network failure',async()=>{const c=make(async()=>{throw new Error('offline');});c.saveSession(session);await assert.rejects(c.logout());assert.equal(c.session,null);});
test('unsafe table and RPC names are rejected',async()=>{const c=make(async()=>{throw new Error('Unexpected fetch');});await assert.rejects(c.select('auth.users'));await assert.rejects(c.rpc('../unsafe',{}));});
