import Link from 'next/link';
import {Plus,ArrowRight} from 'lucide-react';
import {Heading,Stat,Card,Table,Status,Pagination,Empty,queryLink,Notice} from '@/components/ui';
import {FiltersBar} from '@/components/filters';
import {CatalogFilter} from '@/features/catalog-filter';
import {DeleteDraft} from '@/features/draft-actions';
import {documents,entity} from '@/lib/server/data';
import {parseFilters} from '@/lib/schemas';
import {money} from '@/lib/money';
import {displayDate} from '@/lib/dates';
import type {SearchParams} from '@/features/catalog-pages';
import type {Purchase,Supplier} from '@/lib/domain';
export default async function Page({searchParams}:{searchParams:Promise<SearchParams>}){const params=await searchParams,filters=parseFilters(params);const [data,supplier]=await Promise.all([documents<Purchase>('purchases',filters),filters.supplier?entity<Supplier>('suppliers',filters.supplier):Promise.resolve(null)]);return <><Heading eyebrow="Operations / Purchases" title="Purchase history" description="Review received purchases or continue a saved draft." actions={<Link className="button primary" href="/purchases/new"><Plus size={15}/>New purchase</Link>}/><div className="stats three"><Stat label="Received purchase value" value={money(data.total_paisa??'0')} note="Matching search, supplier and dates · excludes drafts" icon="bag"/><Stat label="Received purchases" value={data.received_count??0} note="Goods already added to inventory" color="blue"/><Stat label="Saved drafts" value={data.draft_count??0} note="No stock or received-total effect" color="amber"/></div><nav className="tabs" aria-label="Purchase status">{[{key:'',label:'All purchases'},{key:'received',label:'Received'},{key:'draft',label:'Drafts'}].map(tab=><Link key={tab.key} href={queryLink('/purchases',params,{status:tab.key,page:undefined})} className={(filters.status??'')===tab.key?'active':''}>{tab.label}</Link>)}</nav><FiltersBar dates><CatalogFilter kind="suppliers" initial={supplier}/></FiltersBar><Card><Table headers={['Purchase','Activity date','Supplier','Products','Total','Status','Action']} empty={!data.rows.length?<Empty title="No purchases found" description="Record goods received or save a draft for later." href="/purchases/new" action="New purchase"/>:undefined}>{data.rows.map(p=><tr key={p.id}><td><strong>{p.number}</strong></td><td>{displayDate(p.activity_at)}<small className="muted" style={{display:'block'}}>Invoice: {displayDate(p.purchase_date)}</small></td><td>{p.supplier_name}</td><td>{p.product_count} products</td><td><strong>{money(p.total_paisa)}</strong></td><td><Status status={p.status}/></td><td><div className="row"><Link className="table-action" href={`/purchases/${p.id}${p.status==='draft'?'/edit':''}`}>{p.status==='draft'?'Continue':'View'}<ArrowRight size={12}/></Link>{p.status==='draft'&&<DeleteDraft id={p.id} version={p.version} number={p.number}/>}</div></td></tr>)}</Table><Pagination data={data} path="/purchases" params={params}/></Card><div style={{marginTop:18}}><Notice>Date filters use the actual received time for posted purchases and the last saved time for drafts. Invoice dates do not backdate stock.</Notice></div></>}
