import Link from 'next/link';
import {redirect} from 'next/navigation';
import {History,Check,ArrowRight} from 'lucide-react';
import {Heading,Card,Table,Notice,Status} from '@/components/ui';
import {PrintButton} from '@/features/print';
import {entity} from '@/lib/server/data';
import {money} from '@/lib/money';
import {displayDate} from '@/lib/dates';
import type {Purchase} from '@/lib/domain';
export default async function Page({params}:{params:Promise<{id:string}>}){const p=await entity<Purchase>('purchases',(await params).id);if(p.status==='draft')redirect(`/purchases/${p.id}/edit`);return <><Heading eyebrow="Operations / Purchases / Details" title={`Purchase ${p.number}`} description="Received purchase details and its historical stock impact." actions={<><Link className="button" href={`/inventory/movements?document=${p.id}`}><History size={15}/>Stock history</Link><PrintButton/></>}/><div className="stack print-document"><div className="document-banner"><span className="row"><Check size={16}/>This purchase has been received. Stock was added once.</span><Status status="received"/></div><div className="document-info"><div><label>Supplier</label><strong>{p.supplier_name_snapshot}</strong><small>{p.supplier_phone_snapshot||'Phone not provided'}</small><small>{p.supplier_address_snapshot||'Address not provided'}</small></div><div><label>Purchase / invoice date</label><strong>{displayDate(p.purchase_date)}</strong><small>Reference: {p.supplier_reference||'Not provided'}</small></div><div><label>Received at · Asia/Dhaka</label><strong>{displayDate(p.received_at!,true)}</strong><small>{p.store_name_snapshot}</small><small>{p.store_phone_snapshot||''}</small></div></div><Card title="Received items" description={`${p.items.length} distinct products · ${p.items.reduce((n,i)=>n+i.quantity,0)} selling units`}><Table headers={['Product / SKU','Quantity','Actual unit cost','Line total']}>{p.items.map(i=><tr key={i.id}><td><strong>{i.product_name_snapshot}</strong><small className="muted" style={{display:'block'}}>{i.sku_snapshot}</small></td><td>{i.quantity} {i.unit_snapshot}</td><td>{money(i.unit_cost_paisa)}</td><td><strong>{money(i.line_total_paisa)}</strong></td></tr>)}</Table><div className="card-footer"><div className="between"><span className="muted">Total received purchase value</span><strong className="green" style={{fontSize:24}}>{money(p.total_paisa)}</strong></div></div></Card><Card title="Stock impact" description="Before and after values captured when this purchase was confirmed."><Table headers={['Product','Before','Received','After']}>{p.movements.map(m=><tr key={m.id}><td><strong>{m.product_name}</strong></td><td>{m.quantity_before}</td><td className="green">+{m.quantity_delta}</td><td><strong>{m.quantity_after}</strong></td></tr>)}</Table></Card>{p.note&&<Card title="Purchase note" body><p style={{whiteSpace:'pre-wrap'}}>{p.note}</p></Card>}<div className="card-body"><Notice>Received-goods record, not a payment confirmation or tax invoice. Posted purchases cannot be edited, cancelled or returned in this release. Printing does not change stock.</Notice><Link href="/purchases" className="text-link no-print">Back to purchase history <ArrowRight size={12}/></Link></div></div></>}
