'use client';
import { useRef, useState, useTransition } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { Search } from 'lucide-react';
export function FiltersBar({search=true,stock=false,sort=false,dates=false,statusOptions,children}:{search?:boolean;stock?:boolean;sort?:boolean;dates?:boolean;statusOptions?:{value:string;label:string}[];children?:React.ReactNode}){
 const path=usePathname(),params=useSearchParams(),router=useRouter();const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [pending,startTransition]=useTransition();
 const [from,setFrom]=useState(params.get('from')??'');const [to,setTo]=useState(params.get('to')??'');
 function update(changes:Record<string,string>){const next=new URLSearchParams(params);next.delete('page');for(const[k,v]of Object.entries(changes)){if(v)next.set(k,v);else next.delete(k);}startTransition(()=>router.replace(`${path}${next.size?'?'+next.toString():''}`,{scroll:false}));}
 return <div className="filters no-print" aria-busy={pending}>{search&&<div className="search-input"><Search size={16}/><label className="sr-only" htmlFor="list-search">Search records</label><input key={params.get('q')??''} id="list-search" type="search" defaultValue={params.get('q')??''} placeholder="Search by name, SKU or reference" maxLength={150} onChange={e=>{const value=e.currentTarget.value;if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>update({q:value}),300);}}/></div>}{children}{stock&&<select aria-label="Stock status" value={params.get('stock')??''} onChange={e=>update({stock:e.target.value})}><option value="">All stock statuses</option><option value="in_stock">In stock</option><option value="low_stock">Low stock</option><option value="out_of_stock">Out of stock</option></select>}{statusOptions&&<select aria-label="Record status" value={params.get('status')??''} onChange={e=>update({status:e.target.value})}><option value="">All types</option>{statusOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>}{sort&&<select className="sort" aria-label="Sort records" value={params.get('sort')??'name_asc'} onChange={e=>update({sort:e.target.value})}><option value="name_asc">Name: A–Z</option><option value="name_desc">Name: Z–A</option><option value="stock_asc">Stock: low to high</option><option value="stock_desc">Stock: high to low</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="newest">Newest first</option></select>}{dates&&<div className="date-filters"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="button" type="button" onClick={()=>{if(from&&to)update({from,to});else if(!from&&!to)update({from:'',to:''});}} disabled={!!from!==!!to}>Apply dates</button>{params.has('from')&&<button className="text-link" onClick={()=>{setFrom('');setTo('');update({from:'',to:''});}}>Clear dates</button>}</div>}<select aria-label="Rows per page" value={params.get('size')??'20'} onChange={e=>update({size:e.target.value})}><option value="20">20 / page</option><option value="50">50 / page</option><option value="100">100 / page</option></select></div>;
}
