'use client';
import { useEffect, useState } from 'react';
import { ChevronDown, Search } from 'lucide-react';
import { Dialog } from './dialog';
import { ProductIcon } from './brand';
import { Notice } from './ui';
import type { CatalogKind, Product, Category, Supplier, PageResult } from '@/lib/domain';
export type Pickable=Product|Category|Supplier;
export function Picker({kind,value,label,onSelect,disabled=false,id,extra}:{kind:CatalogKind;value?:{id:string;name:string}|null;label:string;onSelect:(item:Pickable)=>void;disabled?:boolean;id?:string;extra?:React.ReactNode}){
 const [open,setOpen]=useState(false),[q,setQ]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<PageResult<Pickable>|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError('');fetch(`/api/catalog?kind=${kind}&q=${encodeURIComponent(q)}&page=${page}&size=20`,{signal:controller.signal,cache:'no-store'}).then(r=>r.json()).then(result=>{if(result.error)throw new Error(result.error.message);setData(result);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load records.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[kind,q,page,open]);
 return <div className="picker"><button type="button" id={id} className="button picker-trigger" disabled={disabled} onClick={()=>setOpen(true)} aria-haspopup="dialog">{value?.name??label}<ChevronDown size={15}/></button><Dialog open={open} onClose={()=>setOpen(false)} title={label}><div className="search-input" style={{width:'100%'}}><Search size={16}/><label className="sr-only" htmlFor={`picker-search-${kind}`}>Search {kind}</label><input id={`picker-search-${kind}`} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} type="search" autoComplete="off" placeholder={`Search ${kind}`} autoFocus/></div>{error&&<Notice tone="error">{error}</Notice>}<div className="picker-list" aria-busy={loading}>{loading&&<p className="muted">Loading…</p>}{!loading&&data?.rows.map(item=><button type="button" className="picker-option" key={item.id} onClick={()=>{onSelect(item);setOpen(false);}}><ProductIcon icon={'icon_key'in item?item.icon_key:'store'} color={'color_key'in item?item.color_key:'blue'}/><span><strong>{item.name}</strong><small>{'sku'in item?`${item.sku} · ${item.quantity} ${item.unit} available`:''}</small></span></button>)}{!loading&&data?.total===0&&<p className="muted">No matching {kind}.</p>}</div><div className="between"><button className="button" type="button" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><small className="muted">Page {page} · {data?.total??0} records</small><button className="button" type="button" disabled={!data||page*20>=data.total||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div>{extra}</Dialog></div>;
}
