import type { ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight, ChevronLeft, ChevronRight, Package, Info } from 'lucide-react';
import { ProductIcon } from './brand';
import type { PageResult } from '@/lib/domain';
export function Heading({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:ReactNode}){return <header className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{actions&&<div className="page-actions">{actions}</div>}</header>}
export function Card({title,description,action,children,className='',body=false}:{title?:string;description?:string;action?:ReactNode;children:ReactNode;className?:string;body?:boolean}){return <section className={`card ${className}`}>{title&&<div className="card-head"><div><h3>{title}</h3>{description&&<p>{description}</p>}</div>{action}</div>}{body?<div className="card-body">{children}</div>:children}</section>}
export function Stat({label,value,note,icon='package',color='emerald'}:{label:string;value:string|number;note:string;icon?:string;color?:string}){return <section className="card stat"><ProductIcon icon={icon} color={color} size={19}/><p className="stat-label">{label}</p><strong>{value}</strong><p className="stat-note">{note}</p></section>}
export function Notice({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'warning'|'error'|'success'}){return <div className={`notice ${tone==='success'?'':tone}`} role={tone==='error'?'alert':undefined}><Info size={17}/><div>{children}</div></div>}
export function Empty({title='Nothing here yet',description='Your store has no records to show.',href,action}:{title?:string;description?:string;href?:string;action?:string}){return <div className="empty"><Package size={29} strokeWidth={1.4}/><h3>{title}</h3><p>{description}</p>{href&&<Link href={href} className="button primary">{action??'Get started'}<ArrowRight size={14}/></Link>}</div>}
export function Status({status}:{status:string}){const labels:Record<string,string>={in_stock:'In stock',low_stock:'Low stock',out_of_stock:'Out of stock',draft:'Draft',received:'Received',completed:'Completed'};return <span className={`badge badge-dot ${status}`}>{labels[status]??status}</span>}
export function ProductLabel({name,sku,icon_key,color_key}:{name:string;sku?:string;icon_key?:string;color_key?:string}){return <span className="product-cell"><ProductIcon icon={icon_key} color={color_key}/><span><strong>{name}</strong>{sku&&<small>{sku}</small>}</span></span>}
export function Field({label,id,children,hint,error,className=''}:{label:string;id:string;children:ReactNode;hint?:string;error?:string;className?:string}){return <div className={`field ${className}`}><label htmlFor={id}>{label}</label>{children}{hint&&<small id={`${id}-hint`}>{hint}</small>}{error&&<span className="field-error" id={`${id}-error`}>{error}</span>}</div>}
export function Table({headers,children,empty}:{headers:string[];children:ReactNode;empty?:ReactNode}){return <div className="data-table-wrap" role="region" aria-label="Scrollable data table" tabIndex={0}><table className="data-table"><thead><tr>{headers.map((label,i)=><th key={i} scope="col">{label}</th>)}</tr></thead><tbody>{children}</tbody></table>{empty}</div>}
export function queryLink(path:string,params:Record<string,string|string[]|undefined>,changes:Record<string,string|number|undefined>={}){const q=new URLSearchParams();for(const[k,v]of Object.entries(params))if(typeof v==='string'&&v)q.set(k,v);for(const[k,v]of Object.entries(changes)){if(v===undefined||v==='')q.delete(k);else q.set(k,String(v));}return path+(q.size?'?'+q.toString():'');}
export function Pagination({data,path,params}:{data:Pick<PageResult<unknown>,'total'|'page'|'size'>;path:string;params:Record<string,string|string[]|undefined>}){const pages=Math.max(1,Math.ceil(data.total/data.size));return <footer className="pagination"><span>{data.total?`Showing ${Math.min((data.page-1)*data.size+1,data.total)}–${Math.min(data.page*data.size,data.total)} of ${data.total}`:'No matching records'}</span><div className="row">{data.page>1?<Link className="icon-button" href={queryLink(path,params,{page:data.page-1})} aria-label="Previous page"><ChevronLeft size={16}/></Link>:<span className="icon-button" aria-hidden="true"><ChevronLeft size={16}/></span>}<span className="page-number">{data.page} / {pages}</span>{data.page<pages?<Link className="icon-button" href={queryLink(path,params,{page:data.page+1})} aria-label="Next page"><ChevronRight size={16}/></Link>:<span className="icon-button" aria-hidden="true"><ChevronRight size={16}/></span>}</div></footer>}
export function ReportTabs({active}:{active:string}){return <nav className="tabs" aria-label="Report types">{['sales','purchases','inventory'].map(kind=><Link key={kind} href={`/reports/${kind}`} className={active===kind?'active':''}>{kind==='purchases'?'Purchase':kind[0].toUpperCase()+kind.slice(1)} report</Link>)}</nav>}
