import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import {Heading,Card,Table,ProductLabel,Pagination,Empty,Notice} from '@/components/ui';
import {FiltersBar} from '@/components/filters';
import {CatalogFilter} from '@/features/catalog-filter';
import {documents,entity} from '@/lib/server/data';
import {parseFilters} from '@/lib/schemas';
import {displayDate} from '@/lib/dates';
import type {SearchParams} from '@/features/catalog-pages';
import type {Movement,Product} from '@/lib/domain';
export default async function Page({searchParams}:{searchParams:Promise<SearchParams>}){const params=await searchParams,filters=parseFilters(params);const [data,product]=await Promise.all([documents<Movement>('movements',filters),filters.product?entity<Product>('products',filters.product):Promise.resolve(null)]);return <><Heading eyebrow="Stock control / History" title="Stock movement" description="Trace each stock change to a received purchase or completed sale." actions={<Link className="button" href="/inventory">Current inventory</Link>}/><div style={{marginBottom:22}}><Notice tone="success">This ledger is read-only. Before and after quantities describe each historical posting, ordered by its database ledger sequence.</Notice></div>{filters.document&&<div className="button-row" style={{marginBottom:18}}><span className="badge">Filtered to one source document</span><Link className="text-link" href="/inventory/movements">Clear document filter</Link></div>}<FiltersBar dates statusOptions={[{value:'purchase',label:'Purchase received'},{value:'sale',label:'Sale completed'}]}><CatalogFilter kind="products" initial={product}/></FiltersBar><Card><Table headers={['Posted at · Dhaka','Product','Source','Reference','Change','Before','After']} empty={!data.rows.length?<Empty title="No movements found" description="Only receiving purchases and completing sales create stock movements." href="/purchases/new" action="Record purchase"/>:undefined}>{data.rows.map(m=><tr key={m.id}><td>{displayDate(m.created_at,true)}<small className="muted" style={{display:'block'}}>Ledger #{m.sequence}</small></td><td><ProductLabel name={m.product_name} sku={m.sku} icon_key={m.icon_key} color_key={m.color_key}/></td><td><span className={`badge ${m.source_type==='purchase'?'received':'draft'}`}>{m.source_type==='purchase'?'Purchase received':'Sale completed'}</span></td><td><Link href={`/${m.source_type==='purchase'?'purchases':'sales'}/${m.source_id}`} className="table-action">{m.number}<ArrowUpRight size={12}/></Link></td><td><strong className={m.quantity_delta>0?'green':'red'}>{m.quantity_delta>0?'+':''}{m.quantity_delta}</strong></td><td>{m.quantity_before}</td><td><strong>{m.quantity_after}</strong></td></tr>)}</Table><Pagination data={data} path="/inventory/movements" params={params}/></Card></>}
