import {config as deployed} from '/config.js';
import {SupabaseClient} from './supabase.js';
import {escapeHtml as e,validateConfig,cleanText,uuid,isManager,money,dateLabel,number} from './core.js';
import {icon,button,heading,empty,metric,panel,chart,badge,table,field,select,toast,showError,bindActions,formSubmit,modal} from './ui.js';
const root=document.getElementById('app');
const brand=`<a class="brand" href="#dashboard"><span class="brand-icon">${icon('cube')}</span><span>Smart Inventory<small>Inventory & point of sale</small></span></a>`;
const nav=[['dashboard','Overview','dashboard'],['pos','Point of sale','cart'],['products','Products','cube'],['categories','Categories','tag','manager'],['purchases','Purchases','purchase','manager'],['sales','Sales history','history'],['customers','Customers','users'],['suppliers','Suppliers','truck','manager'],['inventory','Stock movements','refresh','manager'],['reports','Reports','chart','manager'],['assistant','AI assistant','spark','manager'],['settings','Settings','settings','owner']];
const app={client:null,user:null,org:null,orgs:[],role:'',route:'dashboard',pageId:0};
app.money=v=>money(v,app.org?.currency||'BDT');
app.date=(v,t=false)=>dateLabel(v,app.org?.timezone||'Asia/Dhaka',t);
app.manager=()=>isManager(app.role);
app.select=(tableName,query={})=>app.client.select(tableName,{org_id:`eq.${app.org.id}`,...query});
app.mutate=async(action,payload)=>{
  const scope=`si-pending:${app.client.url}:${app.user.id}:${app.org.id}`;
  let pending;try{pending=JSON.parse(sessionStorage.getItem(scope)||'null');}catch{}
  const signature=JSON.stringify({action,payload});
  if(pending&&pending.signature!==signature) throw new Error('A previous request has an uncertain result. Use Resolve pending request before making another change.');
  pending ||= {key:uuid(),signature,action,payload};sessionStorage.setItem(scope,JSON.stringify(pending));
  try{const result=await app.client.mutate(app.org.id,action,payload,pending.key);sessionStorage.removeItem(scope);return result;}
  catch(error){if(error.code!=='NETWORK'&&error.status<500)sessionStorage.removeItem(scope);throw error;}
};
app.lookup=async(tableName)=>{let all=[],offset=0;for(;;){const {data}=await app.select(tableName,{active:'eq.true',order:'name.asc',limit:500,offset});all.push(...data);if(data.length<500)break;offset+=500;if(offset>=10000)throw new Error('Too many lookup records. Narrow your catalog before using this operation.');}return all;};
app.refresh=()=>route();
function authLayout(content){root.innerHTML=`<div class="auth-layout"><aside class="auth-story">${brand}<div class="auth-story-content"><p class="eyebrow">A LITTLE LESS BUSYWORK.</p><h1>Your inventory.<br>Your business.<br><em>All together.</em></h1><p>A clearer view of your stock, a smoother checkout, and more time for the business you love.</p><div class="auth-art" aria-hidden="true"><div class="art-box">${icon('cube')}</div><div class="art-box">${icon('chart')}</div><div class="art-box">${icon('cart')}</div></div><div class="auth-proof">${icon('lock')}Your workspace. Your data. Securely connected.</div></div><div class="auth-story-footer">SMART INVENTORY · PURCHASES · POINT OF SALE</div></aside><main id="main" class="auth-main"><div class="auth-card"><div class="auth-mobile-brand">${brand}</div>${content}</div></main></div>`;}
function setup(){authLayout(`<p class="eyebrow">LET’S CONNECT YOUR BUSINESS</p><h1>Connect to Supabase</h1><p class="muted">Your application is ready for a dedicated database. No sample records or local-only inventory will be used.</p><form class="form-stack" id="setup-form">${field('url','Supabase project URL','','url','required placeholder="https://your-project.supabase.co"')}${field('key','Publishable key','','text','required autocomplete="off" placeholder="sb_publishable_…"')}<div class="notice">Use only a publishable or legacy anon key. Never enter a secret or service-role key. Apply the three inventory migrations to your dedicated project first.</div><div data-error></div><button class="button primary" type="submit">Connect workspace ${icon('arrow')}</button></form><div class="setup-steps"><p><b>01</b>Create or select a dedicated Supabase project.</p><p><b>02</b>Apply migrations and configure authentication redirects.</p><p><b>03</b>Set deployment environment variables for all users.</p></div><p class="footer-note">This browser configuration is stored only for this tab. A deployment administrator should configure the environment for production.</p>`);formSubmit(document.getElementById('setup-form'),async({url,key})=>{const c=validateConfig(url,key);const client=new SupabaseClient(c);await client.raw('/auth/v1/settings');sessionStorage.setItem('si-public-config',JSON.stringify(c));app.client=client;login();});}
function login(mode='login',message=''){
  const reset=mode==='reset',signup=mode==='signup',password=mode==='password';
  authLayout(`<span class="connection">Supabase connected</span><h1>${password?'Choose a new password':reset?'Reset your password':signup?'Create your account':'Welcome back'}</h1><p class="muted">${password?'Choose at least 12 characters to secure your account.':reset?'We’ll send you a secure password reset link.':signup?'Start with your account, then create or join a workspace.':'Sign in to manage your store, stock, and sales.'}</p>${message?`<div class="notice success" role="status">${e(message)}</div>`:''}<form id="auth-form" class="form-stack">${!password?field('email','Email address','','email','required autocomplete="email" maxlength="254"'):''}${!reset?field('password','Password','','password',`required autocomplete="${signup||password?'new-password':'current-password'}" minlength="${signup||password?12:1}" maxlength="128"`):''}${signup||password?field('confirm','Confirm password','','password','required autocomplete="new-password" minlength="12" maxlength="128"'):''}<div data-error></div><button class="button primary" type="submit">${password?'Update password':reset?'Send reset link':signup?'Create account':'Sign in'} ${icon('arrow')}</button></form><div class="auth-links">${!password?`<button class="button text-button" data-action="${signup||reset?'login':'signup'}">${signup||reset?'Back to sign in':'Create an account'}</button>${!signup&&!reset?'<button class="button text-button" data-action="reset">Forgot password?</button>':''}`:''}</div><p class="footer-note">Accounts and inventory are stored in Supabase. This application does not process card or mobile-wallet charges.</p>`);
  bindActions(root,{login:()=>login(),signup:()=>login('signup'),reset:()=>login('reset')});
  formSubmit(document.getElementById('auth-form'),async(data)=>{
    if(signup||password){if(data.password!==data.confirm)throw new Error('Passwords do not match.');if(data.password.length<12)throw new Error('Use at least 12 characters.');}
    if(reset){await app.client.recover(data.email,location.origin);login('login','When an account exists, a reset link will be sent to that address.');return;}
    if(password){await app.client.updatePassword(data.password);history.replaceState(null,'',location.pathname+'#dashboard');toast('Password updated.');await loadWorkspace();return;}
    if(signup){await app.client.signup(data.email,data.password,location.origin);if(!app.client.session){login('login','Check your email to confirm your account before signing in.');return;}}
    else await app.client.login(data.email,data.password);
    await loadWorkspace();
  });
}
function onboarding(error=''){
  authLayout(`<p class="eyebrow">YOUR NEW WORKSPACE</p><h1>Make it your own</h1><p class="muted">Create your business workspace, or ask its owner to add your registered email address.</p>${error?`<div class="notice danger">${e(error)}</div>`:''}<form id="workspace-form" class="form-stack">${field('name','Business name','','text','required maxlength="160" placeholder="Your business"')}<div class="form-grid">${select('currency','Currency',[['BDT','BDT · Bangladeshi taka'],['USD','USD · US dollar'],['EUR','EUR · Euro'],['GBP','GBP · British pound'],['INR','INR · Indian rupee']], 'BDT')}${field('timezone','Business timezone','Asia/Dhaka','text','required maxlength="80"')}</div><div data-error></div><button class="button primary" type="submit">Create workspace ${icon('arrow')}</button></form><div class="auth-links">${button('Check membership','reload','text-button')}${button('Sign out','logout','text-button')}</div>`);
  const key=sessionStorage.getItem('si-bootstrap-key')||uuid();sessionStorage.setItem('si-bootstrap-key',key);
  formSubmit(document.getElementById('workspace-form'),async(data)=>{await app.client.rpc('si_bootstrap',{p_name:cleanText(data.name,'Business name'),p_currency:data.currency,p_timezone:data.timezone,p_key:key});sessionStorage.removeItem('si-bootstrap-key');await loadWorkspace();});bindActions(root,{reload:loadWorkspace,logout});
}
async function loadWorkspace(){
  app.user=await app.client.user();
  const {data:members}=await app.client.select('si_members',{user_id:`eq.${app.user.id}`,active:'eq.true'});
  const {data:orgs}=await app.client.select('si_organizations',{order:'name.asc'});
  app.orgs=orgs.map(o=>({...o,role:members.find(m=>m.org_id===o.id)?.role})).filter(o=>o.role);
  if(!app.orgs.length){onboarding();return;}
  const pref=sessionStorage.getItem(`si-org:${app.user.id}`);app.org=app.orgs.find(o=>o.id===pref)||app.orgs[0];app.role=app.org.role;shell();await route();
}
async function logout(){try{await app.client.logout();}finally{app.user=null;app.org=null;app.pageId++;document.getElementById('modal-root').innerHTML='';login();}}
function shell(){
  const allowed=nav.filter(n=>!n[3]||n[3]==='manager'&&app.manager()||n[3]==='owner'&&app.role==='owner');
  root.innerHTML=`<button class="mobile-backdrop" aria-label="Close navigation"></button><aside class="sidebar">${brand}<div class="nav-label">WORKSPACE</div><nav aria-label="Main navigation">${allowed.map(([path,title,ico])=>`<a class="nav-link" href="#${path}" data-route="${path}">${icon(ico)}${e(title)}</a>`).join('')}</nav><div class="sidebar-footer"><button class="nav-link" data-action="logout" style="border:0;background:none;width:100%">${icon('logout')}Sign out</button><div class="workspace-card"><span class="avatar">${e(app.org.name.slice(0,1).toUpperCase())}</span><div><strong>${e(app.org.name)}</strong><small>${e(app.role)} workspace</small></div></div></div></aside><div class="app-shell"><header class="topbar"><div class="topbar-left"><button class="icon-button mobile-toggle" data-action="menu" aria-label="Open navigation" aria-expanded="false">${icon('menu')}</button><span class="muted">Workspace <span style="margin:0 9px">/</span> <span id="breadcrumb">Overview</span></span></div><div class="topbar-right"><span class="connection">Supabase</span><select aria-label="Switch workspace" id="workspace-switch">${app.orgs.map(o=>`<option value="${o.id}" ${o.id===app.org.id?'selected':''}>${e(o.name)}</option>`).join('')}</select><button class="icon-button" data-action="refresh" aria-label="Refresh records">${icon('refresh')}</button><span class="avatar" title="${e(app.user.email)}">${e(app.user.email?.slice(0,1).toUpperCase()||'U')}</span></div></header><main id="main" class="main" tabindex="-1"></main></div>`;
  const closeMenu=()=>{root.querySelector('.sidebar').classList.remove('open');root.querySelector('.mobile-backdrop').classList.remove('open');root.querySelector('.mobile-toggle').setAttribute('aria-expanded','false');};
  bindActions(root,{logout,refresh:()=>route(),menu:()=>{root.querySelector('.sidebar').classList.toggle('open');root.querySelector('.mobile-backdrop').classList.toggle('open');root.querySelector('.mobile-toggle').setAttribute('aria-expanded',root.querySelector('.sidebar').classList.contains('open'));}});
  root.querySelector('.mobile-backdrop').onclick=closeMenu;root.querySelectorAll('.nav-link').forEach(n=>n.addEventListener('click',closeMenu));
  document.getElementById('workspace-switch').onchange=async event=>{app.pageId++;document.getElementById('modal-root').innerHTML='';app.org=app.orgs.find(o=>o.id===event.target.value);app.role=app.org.role;sessionStorage.setItem(`si-org:${app.user.id}`,app.org.id);shell();await route();};
}
async function dashboard(node){
  const d=await app.client.rpc('si_dashboard',{p_org:app.org.id});
  node.innerHTML=heading('Overview',`Here’s what’s happening at ${app.org.name} today.`,button('Open point of sale','pos','primary','cart'))+`<div class="metrics">${metric('Today’s net sales',app.money(d.today_sales_minor-d.today_returns_minor),'Gross sales minus returns today','chart','featured')}${metric('Orders today',number(d.today_orders),'All completed checkout records','cart')}${metric('Active products',number(d.product_count),`${number(d.stock_units)} units on hand`,'cube')}${metric('Low-stock products',number(d.low_stock_count),'At or below reorder level','alert')}</div><div class="grid">${panel('Sales overview',chart(d.daily,app.org.currency)+'<div class="chart-note">Gross daily sales · last 7 days · '+e(app.org.timezone)+'</div>',app.manager()?'<a href="#reports">View reports →</a>':'')}${panel('Stock needs attention',d.low_stock.length?d.low_stock.map(p=>`<div class="item-row"><span class="product-icon">${icon('cube')}</span><div class="grow"><h3>${e(p.name)}</h3><small>${e(p.sku)}</small></div>${badge(`${p.stock} ${p.unit} left`,'amber')}</div>`).join(''):empty('Stock is looking good','No active product is at or below its reorder level.'),'<a href="#products">View all →</a>')}</div>${panel('Recent sales',d.recent_sales.length?table(['Sale','Date','Total','Status',''],d.recent_sales.map(s=>`<tr><td><strong>${e(s.reference)}</strong></td><td>${e(app.date(s.created_at))}</td><td>${e(app.money(s.total_minor))}</td><td>${badge(s.status)}</td><td><a href="#sales?id=${s.id}">View receipt →</a></td></tr>`)):empty('Your first sale starts here','Add your products, receive a purchase, then make your first checkout.'),'<a href="#sales">All sales →</a>')}<p class="footer-note">Figures are calculated from your Supabase workspace. Returns are counted on their return date; no payment gateway is connected.</p>`;
  bindActions(node,{pos:()=>location.hash='pos'});
}
async function route(){
  if(!app.org||!document.getElementById('main'))return;
  const [path,query='']=location.hash.slice(1).split('?');app.route=path||'dashboard';app.params=new URLSearchParams(query);const target=nav.find(n=>n[0]===app.route);
  const main=document.getElementById('main');main.innerHTML='<div class="loading" role="status">Loading your workspace…</div>';const node=document.createElement('div');const generation=++app.pageId;
  root.querySelectorAll('[data-route]').forEach(a=>{a.classList.toggle('active',a.dataset.route===app.route);if(a.dataset.route===app.route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.getElementById('breadcrumb').textContent=target?.[1]||'Not found';document.title=`${target?.[1]||'Smart Inventory'} · Smart Inventory`;
  try{
    if(!target)node.innerHTML=empty('Page not found','Choose a page from the navigation.');
    else if(target[3]==='manager'&&!app.manager()||target[3]==='owner'&&app.role!=='owner')node.innerHTML=empty('Access restricted','Your workspace role does not permit this page.');
    else if(app.route==='dashboard')await dashboard(node);
    else if(['products','categories','customers','suppliers','inventory'].includes(app.route))await (await import('./catalog.js')).render(app,node);
    else if(['pos','purchases','sales'].includes(app.route))await (await import('./commerce.js')).render(app,node);
    else if(['reports','settings'].includes(app.route))await (await import('./reports.js')).render(app,node);
    else if(app.route==='assistant')await (await import('./assistant.js')).render(app,node);
    if(generation!==app.pageId)return;main.replaceChildren(node);
    const pending=sessionStorage.getItem(`si-pending:${app.client.url}:${app.user.id}:${app.org.id}`);
    if(pending){const banner=document.createElement('div');banner.className='notice danger';banner.innerHTML=`A previous change has an uncertain result. ${button('Resolve pending request','resolve','secondary')}`;main.prepend(banner);bindActions(banner,{resolve:()=>modal('Resolve uncertain request','<p class="muted">Retry the exact stored request with its original idempotency key. This checks the original outcome without creating a duplicate transaction.</p>',{submit:'Retry original request',onSubmit:async(_,__,dialog)=>{const p=JSON.parse(pending);const result=await app.mutate(p.action,p.payload);if(p.action==='sale_checkout'){sessionStorage.removeItem(`si-cart:${app.client.url}:${app.user.id}:${app.org.id}`);history.replaceState(null,'',location.pathname+location.search+`#sales?id=${result.id}`);}dialog.close();toast('Original request resolved. Records refreshed.');await route();}})});}
  }catch(error){if(generation!==app.pageId)return;main.innerHTML='';showError(main,error);const b=document.createElement('button');b.className='button secondary';b.textContent='Retry';b.onclick=()=>route();main.append(b);if(error.status===401){app.org=null;login('login','Your session expired. Please sign in again.');}}
}
async function start(){
  let settings=deployed;try{if(!settings.supabaseUrl)settings=JSON.parse(sessionStorage.getItem('si-public-config')||'null')||settings;}catch{}
  const fragment=location.hash;const authFragment=/access_token=|error_description=/.test(fragment);if(authFragment)history.replaceState(null,'',location.pathname+location.search);
  if(!settings.supabaseUrl){setup();return;}
  try{app.client=new SupabaseClient(settings);if(authFragment)await app.client.callback(fragment);if(!app.client.session){login();return;}if(new URLSearchParams(location.search).get('flow')==='recovery'||fragment.includes('type=recovery')){login('password');return;}await loadWorkspace();}
  catch(error){if(!app.client)setup();else if(error.status===401||!app.client.session)login('login',error.message);else onboarding(`Connection setup needs attention: ${error.message}`);}
}
document.querySelector('.skip-link')?.addEventListener('click',event=>{event.preventDefault();const main=document.getElementById('main');main?.setAttribute('tabindex','-1');main?.focus();});
window.addEventListener('hashchange',()=>{if(app.org)route();});window.addEventListener('offline',()=>toast('You are offline. Checkout requires a live server connection.','error'));window.addEventListener('online',()=>toast('Connection restored. Refresh records before checkout.'));start();
