import {escapeHtml as e,parseImport,quantity,toMinor,decimal,assert} from './core.js';
import {icon,heading,button,panel,table,empty,select,area,modal,formSubmit,bindActions,toast} from './ui.js';
import {purchaseEditor} from './commerce.js';
export async function render(app,node){
  node.innerHTML=heading('AI assistant','A second pair of eyes. You stay in control of every decision.')+`<div class="ai-hero">${icon('spark')}<div><h2>Less typing. More clarity.</h2><p>Review purchase text or get a stock-health summary. Suggestions never change your inventory automatically.</p></div></div><div class="grid"><section class="panel"><div class="panel-heading"><h2>Purchase text to draft</h2></div><form class="panel-body form-stack" data-import>${select('mode','Processing mode',[['rules','Structured import · no AI model'],['server','Configured server AI provider']])}${area('text','Purchase or receipt text','','required maxlength="20000" placeholder="SKU, quantity, unit cost\nRICE-1, 10, 120.00"')}<label class="file-control">Load text file (optional)<input type="file" accept=".txt,.csv,text/plain,text/csv" data-file><small>Plain text only, up to 20 KB. Image recognition is not included in this review implementation.</small></label><div class="notice">Structured mode expects one product per line: SKU, quantity, unit cost. Server AI can interpret prose when a provider is configured. Never paste passwords, card numbers, or sensitive personal information.</div><div data-error></div><button type="submit" class="button primary">${icon('spark')}Extract and review</button></form></section><section class="panel"><div class="panel-heading"><h2>Stock-health insights</h2></div><form class="panel-body form-stack" data-insights>${select('mode','Analysis mode',[['rules','Threshold rules · no AI model'],['server','Configured server AI provider']])}<p class="muted">Review low-stock products and potential reorder quantities based on your live workspace.</p><div class="notice">Threshold suggestions are not demand forecasts. A server model receives product names, SKUs and stock levels, but no customer contact records.</div><div data-error></div><button class="button primary" type="submit">${icon('spark')}Analyze stock</button></form><div data-result></div></section></div><p class="footer-note">Provider adapters are replaceable without changing purchase or stock commands. External AI requires server configuration and remains subject to its own accuracy, availability, and data-handling terms.</p>`;
  node.querySelector('[data-file]').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>20000||!/\.(txt|csv)$/i.test(file.name))throw new Error('Select a plain .txt or .csv file up to 20 KB.');node.querySelector('[name=text]').value=await file.text();}catch(err){toast(err.message,'error');event.target.value='';}};
  async function remote(task,text=''){
    const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await app.client.token()}`},body:JSON.stringify({org_id:app.org.id,task,text}),signal:AbortSignal.timeout(45000)});
    let result;try{result=await response.json();}catch{throw new Error('The server assistant endpoint is not configured.');}if(!response.ok)throw new Error(result.error||'Assistant request failed.');assert(result.review_required===true&&result.result,'Invalid assistant response.');return result;
  }
  formSubmit(node.querySelector('[data-import]'),async data=>{
    let result,provider='rules';if(data.mode==='rules')result={kind:'purchase_draft',lines:parseImport(data.text),warnings:['Structured text parser only. No AI model was used.']};else{const response=await remote('purchase',data.text);result=response.result;provider=response.provider;}
    await review(app,result,provider);
  });
  formSubmit(node.querySelector('[data-insights]'),async data=>{
    let result,provider='rules';
    if(data.mode==='server'){const response=await remote('insights');result=response.result;provider=response.provider;}
    else{const context=await app.client.rpc('si_ai_context',{p_org:app.org.id});result={summary:`${context.dashboard.product_count} active products. ${context.dashboard.low_stock_count} products are at or below the reorder level. These are threshold observations, not a sales forecast.`,insights:[{title:context.low_stock.length?'Review these low-stock products':'No low-stock products',detail:'Suggested quantity = twice the reorder threshold minus current stock, with a minimum of one unit. Confirm demand, supplier lead time, and budget before ordering.'}],reorder:context.low_stock.map(p=>({sku:p.sku,quantity:Math.min(1000000,Math.max(1,p.reorder_level*2-p.stock)),reason:'Threshold suggestion; manually review demand.'}))};}
    assert(typeof result.summary==='string'&&Array.isArray(result.insights)&&Array.isArray(result.reorder),'Invalid insight response.');
    node.querySelector('[data-result]').innerHTML=`<div class="ai-result"><span class="badge purple">Provider: ${e(provider)}</span><h3>Stock-health summary</h3><p>${e(result.summary)}</p>${result.insights.map(i=>`<h3>${e(i.title)}</h3><p>${e(i.detail)}</p>`).join('')}${result.reorder.length?`<h3>Suggestions to review</h3>${table(['SKU','Suggested quantity','Reason'],result.reorder.map(r=>`<tr><td>${e(r.sku)}</td><td>${e(r.quantity)}</td><td>${e(r.reason)}</td></tr>`))}`:empty('No reorder suggestions','No stock has been changed.')}</div>`;
  });
}
async function review(app,result,provider){
  assert(result.kind==='purchase_draft'&&Array.isArray(result.lines)&&result.lines.length>0&&result.lines.length<=100,'The provider did not return a valid purchase draft.');const products=await app.lookup('si_products');
  const body=`<div class="notice">Provider: ${e(provider)}. Check every product mapping, quantity and unit cost. Nothing has been saved. Continue opens an editable purchase draft; you must save and receive it separately.</div>${(result.warnings||[]).map(w=>`<p class="muted">${e(w)}</p>`).join('')}${table(['Extracted product','Map to catalog','Quantity','Unit cost'],result.lines.map((l,i)=>{const match=products.find(p=>l.sku&&p.sku.toLowerCase()===String(l.sku).toLowerCase());return `<tr><td><strong>${e(l.name)}</strong><small>${e(l.sku)} · ${Math.round(Number(l.confidence)*100)}% confidence</small>${l.warning?`<small>${e(l.warning)}</small>`:''}</td><td><select name="p_${i}" aria-label="Product mapping ${i+1}" required><option value="">Choose product…</option>${products.map(p=>`<option value="${p.id}" ${p.id===match?.id?'selected':''}>${e(p.name)} · ${e(p.sku)}</option>`).join('')}</select></td><td><input name="q_${i}" aria-label="Quantity ${i+1}" value="${e(l.quantity)}" type="number" min="1" max="1000000" step="1" required></td><td><input name="c_${i}" aria-label="Unit cost ${i+1}" value="${e(decimal(l.unit_cost_minor))}" inputmode="decimal" required></td></tr>`;}))}`;
  modal('Review extracted purchase',body,{wide:true,submit:'Continue to purchase draft',onSubmit:async(data,_,dialog)=>{const lines=result.lines.map((l,i)=>({product_id:data[`p_${i}`],quantity:quantity(data[`q_${i}`]),unit_cost_minor:toMinor(data[`c_${i}`])}));if(new Set(lines.map(l=>l.product_id)).size!==lines.length)throw new Error('Each catalog product can appear only once. Combine duplicate lines in your source text.');if(lines.some(l=>!products.some(p=>p.id===l.product_id)))throw new Error('Map every line to an existing active product.');dialog.close();await purchaseEditor(app,null,lines);}});
}
