import {escapeHtml as e,decimal,toMinor,cleanText,dateKey} from './core.js';
import {heading,button,metric,panel,chart,table,empty,field,select,area,badge,modal,bindActions,formSubmit,downloadCsv,toast} from './ui.js';
export async function render(app,node){return app.route==='settings'?settings(app,node):reports(app,node);}
async function reports(app,node){
  let to=dateKey(new Date(),app.org.timezone),from=to.slice(0,8)+'01',report;
  const labels={sales_minor:'Gross sales',returns_minor:'Sales returns',net_sales_minor:'Net sales including tax',net_tax_minor:'Net tax',revenue_minor:'Revenue excluding tax',cogs_minor:'Cost of goods sold',gross_profit_minor:'Gross profit',collected_minor:'Customer payments less refunds',supplier_paid_minor:'Supplier payments less refunds',net_cash_flow_minor:'Net cash flow',purchase_received_minor:'Purchases received',purchase_returns_minor:'Purchase returns',current_stock_value_minor:'Current stock value',current_receivables_minor:'Current customer receivables',current_payables_minor:'Current supplier payables'};
  async function load(){
    report=await app.client.rpc('si_report',{p_org:app.org.id,p_from:from,p_to:to});const s=report.summary;
    node.innerHTML=heading('Reports','Understand your sales, stock, and cash flow without the spreadsheets.',button('Export report','export','primary','download'))+`<section class="panel"><form class="toolbar" data-report-filter>${field('from','Start date',from,'date','required')}${field('to','End date',to,'date','required')}<button class="button primary" type="submit">Apply range</button><span class="muted">Business timezone: ${e(app.org.timezone)}</span></form></section><div class="metrics">${metric('Net sales',app.money(s.net_sales_minor),'After returns · including tax','chart','featured')}${metric('Gross profit',app.money(s.gross_profit_minor),'Revenue ex-tax minus COGS','chart')}${metric('Current stock value',app.money(s.current_stock_value_minor),'Snapshot now · moving average cost','cube')}${metric('Net cash flow',app.money(s.net_cash_flow_minor),'Customer inflows minus supplier outflows','refresh')}</div><div class="grid">${panel('Sales by day',chart(report.daily,app.org.currency)+'<div class="chart-note">Gross sales by transaction date. Returns are reported on their own event date. Long ranges show sampled days.</div>')}${panel('Current balances',`<div class="panel-body form-stack"><div class="details-line"><span>Customers owe</span><strong>${e(app.money(s.current_receivables_minor))}</strong></div><div class="details-line"><span>You owe suppliers</span><strong>${e(app.money(s.current_payables_minor))}</strong></div><div class="notice">These are current outstanding balances, not historical snapshots for the selected dates.</div></div>`)}</div><div class="grid">${panel('Financial breakdown',table(['Measure','Amount'],Object.entries(labels).filter(([k])=>!k.startsWith('current_')).map(([key,label])=>`<tr><td>${e(label)}</td><td><strong>${e(app.money(s[key]))}</strong></td></tr>`)))}${panel('Top-selling products',report.top_products.length?table(['Product','Units sold','Gross sales'],report.top_products.map(p=>`<tr><td><strong>${e(p.name)}</strong><small>${e(p.sku)}</small></td><td>${p.units_sold}</td><td>${e(app.money(p.sales_minor))}</td></tr>`)):empty('No sales in this range','Try another date range.'))}</div><p class="footer-note">Top products show original units and sales before returns. Gross profit excludes operating expenses; this is not a complete profit-and-loss statement. Amounts use ${e(app.org.currency)}.</p>`;
    formSubmit(node.querySelector('[data-report-filter]'),async data=>{if(data.from>data.to)throw new Error('Start date must be before end date.');from=data.from;to=data.to;await load();});bindActions(node,{export:()=>downloadCsv(`report-${from}-to-${to}.csv`,Object.entries(labels).map(([key,label])=>({measure:label,amount:decimal(s[key]),currency:app.org.currency,from,to,timezone:app.org.timezone})),['measure','amount','currency','from','to','timezone'].map(key=>({key,label:key}))) });
  }
  await load();
}
async function settings(app,node){
  const [{data:orgs},{data:members},{data:audit}]=await Promise.all([app.client.select('si_organizations',{id:`eq.${app.org.id}`}),app.select('si_members',{order:'created_at.asc'}),app.select('si_audit',{order:'created_at.desc',limit:20})]);const org=orgs[0];
  node.innerHTML=heading('Settings','The details that make this workspace yours.')+`<div class="settings-grid"><section class="panel"><div class="panel-heading"><h2>Business details</h2></div><form class="panel-body form-stack" data-settings>${field('name','Business name',org.name,'text','required maxlength="160"')}<div class="form-grid">${select('currency','Currency',['BDT','USD','EUR','GBP','INR','CAD','AUD'].map(c=>[c,c]),org.currency)}${field('timezone','Business timezone',org.timezone,'text','required maxlength="80"')}</div>${area('address','Business address',org.address,'maxlength="500"')}<div class="form-grid">${field('phone','Business phone',org.phone,'tel','maxlength="60"')}${field('tax','Sales tax (%)',decimal(org.tax_bps),'text','required inputmode="decimal"')}</div>${area('receipt_footer','Receipt footer',org.receipt_footer,'maxlength="500"')}<div class="notice">Currency is locked after the first purchase or sale. A tax change affects future checkouts only; original receipts retain their recorded values.</div><div data-error></div><div class="actions"><button class="button primary" type="submit">Save business details</button></div></form></section><div class="stack">${panel('Workspace security',`<div class="panel-body form-stack"><div class="details-line"><span>Signed in as</span><strong>${e(app.user.email)}</strong></div><div class="details-line"><span>Your role</span>${badge(app.role,'purple')}</div><p class="muted">Only owners can change business settings or manage membership. The last active owner cannot be removed.</p>${button('Change password','password','secondary','lock')}</div>`)}${panel('Data & processing',`<div class="panel-body form-stack"><p class="muted">Inventory records live in Supabase. This browser sends only authenticated, tenant-scoped requests.</p><p class="muted">Card and mobile wallet payments are manually recorded. There is no payment processor connected.</p><p class="muted">AI suggestions are reviewable drafts, not automatic stock changes.</p></div>`)}</div></div>${panel('Team members',table(['Email','Role','Status',''],members.map(m=>`<tr><td>${e(m.email)}</td><td>${badge(m.role,'purple')}</td><td>${badge(m.active?'Active':'Inactive',m.active?'green':'gray')}</td><td><button class="button text-button" data-action="member" data-id="${m.user_id}">Edit</button></td></tr>`)),button('Add member','member','secondary','plus'))}<div style="height:22px"></div>${panel('Recent audit trail',audit.length?table(['Date','Action','Actor ID','Entity ID'],audit.map(a=>`<tr><td>${e(app.date(a.created_at,true))}</td><td>${e(a.action.replaceAll('_',' '))}</td><td title="${a.created_by}">${e(a.created_by.slice(0,8))}…</td><td>${e(a.entity_id?.slice(0,8)||'—')}</td></tr>`)):empty('No recorded changes'),'Latest 20 events')}`;
  formSubmit(node.querySelector('[data-settings]'),async data=>{const tax=toMinor(data.tax);if(tax>10000)throw new Error('Tax cannot exceed 100%.');const result=await app.mutate('settings_save',{name:cleanText(data.name,'Business name'),currency:data.currency,timezone:data.timezone,address:data.address,phone:data.phone,receipt_footer:data.receipt_footer,tax_bps:tax});app.org={...app.org,...result};toast('Business details saved.');await settings(app,node);});
  bindActions(node,{password:()=>modal('Change password',`${field('password','New password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}${field('confirm','Confirm password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}`,{submit:'Update password',onSubmit:async(data,_,d)=>{if(data.password!==data.confirm)throw new Error('Passwords do not match.');await app.client.updatePassword(data.password);d.close();toast('Password changed.');}}),member:b=>{
    const m=members.find(m=>m.user_id===b.dataset.id)||{};
    modal(m.user_id?'Edit team member':'Add team member',`<div class="notice">Ask your colleague to register and confirm an account first. This form grants workspace membership; it does not send an invitation email.</div>${field('email','Registered email',m.email||'','email',`required maxlength="254" ${m.user_id?'readonly':''}`)}<div class="form-grid">${select('role','Role',[['cashier','Cashier'],['manager','Manager'],['owner','Owner']],m.role||'cashier')}${select('active','Status',[['true','Active'],['false','Inactive']],String(m.active??true))}</div><p class="muted">Cashiers can sell and manage customers. Managers also manage catalog, purchasing, returns, reports and stock. Owners manage the team and business settings.</p>`,{submit:'Save membership',onSubmit:async(data,_,d)=>{await app.mutate('member_save',{email:data.email,role:data.role,active:data.active==='true'});d.close();toast('Membership updated. Refreshing your permissions.');location.reload();}});
  }});
}
