import { escapeHtml as e, money, csv } from './core.js';
const paths={cube:'m12 3 9 5v8l-9 5-9-5V8l9-5Zm0 9 9-4M12 12 3 8m9 4v9M7.5 5.5l9 5',dashboard:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',cart:'M3 3h2l3 12h10l3-9H6M9 20h.01M18 20h.01',purchase:'M6 3h12v18H6zM9 7h6M9 11h6M9 15h3',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.87M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',truck:'M1 3h13v13H1zM14 8h4l4 4v4h-8M7 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0M21 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0',chart:'M3 3v18h18M7 16v-5M12 16V7M17 16v-8',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',arrow:'M5 12h14m-6-6 6 6-6 6',down:'m6 9 6 6 6-6',menu:'M3 6h18M3 12h18M3 18h18',logout:'M9 5H4v14h5M12 12h9m-4-4 4 4-4 4',refresh:'M20 7v5h-5M4 17v-5h5M6 5a8 8 0 0 1 13 4M5 15a8 8 0 0 0 13 4',check:'m5 12 4 4L19 6',alert:'m12 3 10 18H2L12 3Zm0 6v4m0 4h.01',edit:'m16 3 5 5L8 21H3v-5L16 3Z',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',print:'M6 9V3h12v6M6 18H3V9h18v9h-3M6 14h12v7H6z',history:'M3 3v6h6M3 9a9 9 0 1 1 1 9M12 7v5l3 3',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',tag:'M3 3h8l10 10-8 8L3 11V3Zm4 4h.01',lock:'M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4'};
export const icon=(name,cls='')=>`<svg class="icon ${e(cls)}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.cube}"/></svg>`;
export const button=(text,action,style='primary',ico='')=>`<button type="button" class="button ${style}" data-action="${e(action)}">${ico?icon(ico):''}${e(text)}</button>`;
export const badge=(text,kind='')=>`<span class="badge ${e(kind||(['completed','received'].includes(text)?'green':['cancelled','voided','returned'].includes(text)?'gray':'amber'))}">${e(String(text).replaceAll('_',' '))}</span>`;
export const heading=(title,subtitle,actions='')=>`<div class="page-heading"><div><p class="eyebrow">YOUR BUSINESS, IN SYNC</p><h1>${e(title)}</h1><p class="muted">${e(subtitle)}</p></div><div class="actions">${actions}</div></div>`;
export const empty=(title='No records yet',detail='Your records will appear here once you add them.',action='')=>`<div class="empty">${icon('cube')}<h3>${e(title)}</h3><p>${e(detail)}</p>${action}</div>`;
export const table=(headers,rows)=>`<div class="table-scroll" tabindex="0" aria-label="Scrollable data table"><table><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
export const field=(name,label,value='',type='text',extra='')=>`<label>${e(label)}<input name="${e(name)}" type="${type}" value="${e(value)}" ${extra}></label>`;
export const select=(name,label,options,value='')=>`<label>${e(label)}<select name="${e(name)}">${options.map(([v,l])=>`<option value="${e(v)}" ${String(value)===String(v)?'selected':''}>${e(l)}</option>`).join('')}</select></label>`;
export const area=(name,label,value='',extra='')=>`<label>${e(label)}<textarea name="${e(name)}" rows="3" ${extra}>${e(value)}</textarea></label>`;
export const metric=(title,value,detail,ico='chart',style='')=>`<section class="metric ${style}"><div class="metric-top"><span>${e(title)}</span><span class="metric-icon">${icon(ico)}</span></div><strong>${e(value)}</strong><p>${e(detail)}</p></section>`;
export const panel=(title,body,side='')=>`<section class="panel"><div class="panel-heading"><h2>${e(title)}</h2>${side}</div>${body}</section>`;
export function chart(days,currency='BDT') {
  if(!days?.length)return empty('No chart data');
  const maximum=Math.max(1,...days.map(d=>Number(d.sales_minor)||0));
  const shown=days.length>31?days.filter((_,i)=>i%Math.ceil(days.length/31)===0):days;
  return `<div class="chart" role="img" aria-label="Gross sales over the selected period. Returns are listed separately.">${shown.map(d=>`<div class="bar-column"><div class="bar-space"><div class="bar" style="height:${Math.max(1,Math.round(d.sales_minor/maximum*100))}%" title="${e(d.date)}: ${e(money(d.sales_minor,currency))}"><span>${e(money(d.sales_minor,currency))}</span></div></div><small>${e(d.date.slice(5))}</small></div>`).join('')}</div>`;
}
export function toast(text,kind='success') {const n=document.createElement('div');n.className=`toast ${kind}`;n.textContent=text;document.getElementById('notifications').append(n);setTimeout(()=>n.remove(),7000);}
export function showError(target,error) {target.innerHTML=`<div class="notice danger" role="alert">${e(error.message||error)}</div>`;}
const actionHandlers=new WeakMap();
export function bindActions(root,actions){ if(actionHandlers.has(root))root.removeEventListener('click',actionHandlers.get(root));const handler=event=>{const b=event.target.closest('[data-action]');if(b&&root.contains(b)&&actions[b.dataset.action]){event.preventDefault();Promise.resolve(actions[b.dataset.action](b,event)).catch(err=>toast(err.message,'error'));}};actionHandlers.set(root,handler);root.addEventListener('click',handler); }
export function formSubmit(form,handler) {
  form.addEventListener('submit',async event=>{event.preventDefault();if(form.dataset.busy)return;const err=form.querySelector('[data-error]');if(err)err.innerHTML='';const submit=form.querySelector('[type=submit]');form.dataset.busy='1';if(submit)submit.disabled=true;
    try{await handler(Object.fromEntries(new FormData(form)),form);}catch(error){if(err)showError(err,error);else toast(error.message,'error');}finally{delete form.dataset.busy;if(submit)submit.disabled=false;}
  });
}
export function modal(title,body,{submit='Save',onSubmit,wide=false}={}) {
  const previous=document.activeElement;const dialog=document.createElement('dialog');dialog.className=`dialog ${wide?'wide':''}`;
  const form=onSubmit?'form':'div';dialog.innerHTML=`<${form} class="form-stack"><div class="dialog-heading"><h2>${e(title)}</h2><button type="button" class="icon-button" data-close aria-label="Close dialog">${icon('close')}</button></div>${body}<div data-error></div>${onSubmit?`<div class="dialog-actions"><button type="button" class="button secondary" data-close>Cancel</button><button type="submit" class="button primary">${e(submit)}</button></div>`:''}</${form}>`;
  dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.addEventListener('close',()=>{dialog.remove();if(previous?.isConnected)previous.focus();});
  document.getElementById('modal-root').append(dialog);if(onSubmit)formSubmit(dialog.querySelector('form'),async(data,el)=>{await onSubmit(data,el,dialog);});dialog.showModal();return dialog;
}
export function confirmAction(title,detail,action,run){modal(title,`<p class="muted">${e(detail)}</p>`,{submit:action,onSubmit:async(_,__,dialog)=>{await run();dialog.close();}});}
export function downloadCsv(name,rows,columns){const url=URL.createObjectURL(new Blob([csv(rows,columns)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function pager(page,count,size=20){return `<div class="pagination"><span>${count?`${page*size+1}–${Math.min((page+1)*size,count)} of ${count}`:'0 records'}</span><div><button class="button secondary" data-page="${page-1}" ${page===0?'disabled':''}>Previous</button><button class="button secondary" data-page="${page+1}" ${(page+1)*size>=count?'disabled':''}>Next</button></div></div>`;}
export function searchForm(placeholder,extra=''){return `<form class="toolbar" data-filter><div class="search">${icon('search')}<input name="search" aria-label="${e(placeholder)}" placeholder="${e(placeholder)}" autocomplete="off"></div>${extra}<button class="button secondary" type="submit">Search</button></form>`;}
export const safeSearch=text=>String(text).trim().slice(0,100).replace(/[%_*(),]/g,' ');
