import Link from 'next/link';
import {Plus,Check,ArrowLeft} from 'lucide-react';
import {Heading,Table} from '@/components/ui';
import {Logo} from '@/components/brand';
import {PrintButton} from '@/features/print';
import {entity} from '@/lib/server/data';
import {money} from '@/lib/money';
import {displayDate} from '@/lib/dates';
import type {Sale} from '@/lib/domain';
export default async function Page({params}:{params:Promise<{id:string}>}){const s=await entity<Sale>('sales',(await params).id);return <><Heading eyebrow="Operations / Sales / Receipt" title="Sales receipt" description="A saved record of a completed cash sale." actions={<><PrintButton receipt/><Link className="button primary" href="/pos"><Plus size={15}/>New sale</Link></>}/><article className="print-document receipt" aria-label={`Receipt ${s.number}`}><div className="receipt-header"><div><h2>{s.store_name_snapshot}</h2><small>{s.store_address_snapshot||'Address not provided'}</small>{s.store_phone_snapshot&&<small style={{display:'block'}}>Phone: {s.store_phone_snapshot}</small>}</div><div style={{textAlign:'right'}}><span className="badge completed"><Check size={12}/>Paid · Cash</span><p className="muted small" style={{marginTop:12}}>SALES RECEIPT</p><strong>{s.number}</strong></div></div><div className="receipt-info"><div><span className="muted small">Completed at · Asia/Dhaka</span><strong>{displayDate(s.completed_at,true)}</strong><span className="muted small">Cashier: {s.cashier_name_snapshot}</span></div><div><span className="muted small">Customer</span><strong>{s.customer_name||'Walk-in customer'}</strong>{s.customer_phone&&<span className="muted small">{s.customer_phone}</span>}</div></div><Table headers={['Item','Qty','Price','Amount']}>{s.items.map(i=><tr key={i.id}><td><strong>{i.product_name_snapshot}</strong><small className="muted" style={{display:'block'}}>{i.sku_snapshot} · {i.unit_snapshot}</small></td><td>{i.quantity}</td><td>{money(i.unit_price_paisa)}</td><td><strong>{money(i.line_gross_paisa)}</strong></td></tr>)}</Table><div className="receipt-totals"><dl className="definition-list"><dt>Subtotal</dt><dd>{money(s.subtotal_paisa)}</dd><dt>Order discount</dt><dd>−{money(s.discount_paisa)}</dd></dl><hr/><dl className="definition-list"><dt className="strong">Total paid</dt><dd className="total">{money(s.total_paisa)}</dd><dt>Cash received</dt><dd>{money(s.cash_received_paisa)}</dd><dt>Change returned</dt><dd>{money(s.change_paisa)}</dd></dl></div><footer className="thanks"><strong>Thank you for shopping with us.</strong><small>Paid means sufficient cash tender was recorded by the owner.</small><small>This saved receipt does not change when catalog prices or store details are edited.</small><div className="no-print" style={{marginTop:24,opacity:.7}}><Logo/></div></footer></article><div className="no-print" style={{maxWidth:780,margin:'20px auto'}}><Link href="/sales" className="table-action"><ArrowLeft size={13}/>Back to sales history</Link></div></>}
