import Link from 'next/link';
import {Plus,History} from 'lucide-react';
import {Heading,Stat,Card,Table,ProductLabel,Status,Pagination,Empty,Notice} from '@/components/ui';
import {FiltersBar} from '@/components/filters';
import {CatalogFilter} from '@/features/catalog-filter';
import {catalog,entity,pageWorkspace} from '@/lib/server/data';
import {parseFilters} from '@/lib/schemas';
import {money} from '@/lib/money';
import type {SearchParams} from '@/features/catalog-pages';
import type {Product,Category} from '@/lib/domain';
export default async function Page({searchParams}:{searchParams:Promise<SearchParams>}){const params=await searchParams,filters=parseFilters(params);filters.archived=false;const [data,w,category]=await Promise.all([catalog<Product>('products',filters),pageWorkspace(),filters.category?entity<Category>('categories',filters.category):Promise.resolve(null)]);return <><Heading eyebrow="Stock control / Inventory" title="Current inventory" description="Read-only stock on hand, automatically updated by purchases and sales." actions={<><Link href="/inventory/movements" className="button"><History size={15}/>Stock history</Link><Link href="/purchases/new" className="button primary"><Plus size={15}/>Record purchase</Link></>}/><div className="stats"><Stat label="Estimated stock value" value={money(w.inventory.value_paisa)} note="All active products · ignores table filters"/><Stat label="Active products" value={w.inventory.active_count} note="Whole active catalog" color="blue"/><Stat label="In-stock products" value={w.inventory.in_stock} note="At or above minimum, with positive stock"/><Stat label="Products to review" value={w.inventory.attention_count} note={`${w.inventory.low_stock} low · ${w.inventory.out_of_stock} out`} color="amber"/></div><FiltersBar stock sort><CatalogFilter initial={category}/></FiltersBar><Card><Table headers={['Product','Available','Minimum','Reference unit cost','Estimated value','Status']} empty={!data.rows.length?<Empty title="No inventory matches" description="Add products and receive a purchase, or change the current filters." href="/products/new" action="Add product"/>:undefined}>{data.rows.map(p=><tr key={p.id}><td><ProductLabel name={p.name} sku={p.sku} icon_key={p.icon_key} color_key={p.color_key}/></td><td><strong>{p.quantity}</strong> {p.unit}</td><td>{p.minimum_stock}</td><td>{money(p.reference_cost_paisa)}</td><td><strong>{money(p.stock_value_paisa)}</strong></td><td><Status status={p.stock_status}/></td></tr>)}</Table><div className="card-footer between"><span className="muted small">Filtered estimate · all {data.total} matching products</span><strong>{money(data.filtered_value_paisa??'0')}</strong></div><Pagination data={data} path="/inventory" params={params}/></Card><div style={{marginTop:18}}><Notice>Quantity × current reference purchase cost is an operational estimate, not FIFO, weighted-average accounting or profit. Quantities cannot be edited here.</Notice></div></>}
